### ISSUE TITLE
config/main.ini 配置文件缺失

### ISSUE THREAD

**Issue by MD7sjh** [power-helper/power-helper-backup20210704#101]
**系统版本，包含位数**：

**python版本**：

**软件/源码版本**：

**浏览器、驱动版本**：

-----

## 详细描述
答：

## 全部报错
答：

## 建议
答：

**Comment by rokcso** [comment]
我是使用的源代码运行，也出现了一样的提示，解决办法如下：

`v20210520` 运行 `pandalearning.py` 后会在源代码根目录（`TechXueXi-20210520` 所在的文件夹）自动生成一个名为 `config` 的**空文件夹**，直接将 `v20210316` 或者之前的源代码里的 `config` 文件夹里的 `main.ini` 复制到刚刚自动生成的空的 `config` 文件夹下，即可解决。

**Comment by keke1975** [comment]
这个这个，不是程序员，真不会这东东。有没有可以简单一点的方法呢？

**Comment by TCPsoftware** [comment]
使用打包文件运行，创建config/main.ini后仍提示找不到。如不创建文件夹，也不会自动创建文件夹。

**Comment by waywaywayw** [comment]
好像是运行的相对路径的问题。我的解决方法是：
先cd 到 SourcePackages文件夹。然后再 运行 pandalearning.py

**Comment by dvdrm** [comment]
win平台打好包的文件，出现这个问题怎么解决？

**Comment by thinkrecord** [comment]
使用521新版试试

**Comment by TCPsoftware** [comment]
> 使用521新版试试

测试了，每次打开程序会在 temp 目录产生新的main.ini，以及所有配置
下次打开的时候就不能用了。
base_path = getattr(sys, '_MEIPASS', os.path.abspath('.')) 可用性存疑
建议仍不提供打包文件
