### ISSUE TITLE
v20210521版本 小bug

### ISSUE THREAD

**Issue by jerry-rs** [power-helper/power-helper-backup20210704#111]
**系统版本，包含位数**：

**python版本**：

**软件/源码版本**：

**浏览器、驱动版本**：

-----

## 详细描述
答：v20210521 版本在每周答题结束后，无法退出浏览器，并且控制端，出现报错，其具体报错如下

## 全部报错
答：在answer_question.py 文件的243行`   tips, tip_full_text = driver_weekly._view_tips()`,driver_weekly._view_tips()获取的长度为空，无法赋值给两个变量tips，tip_full_text,其建议如下

## 建议
答：`if len(driver_weekly._view_tips()) != 2:break`，建议代码中增加了长度判断，不满足直接退出循环。

**Comment by TCPsoftware** [comment]
新提交中解决了这个问题，如果没有找到提示信息，返回二元组，长度满足语法，不会语法报错
