### ISSUE TITLE
求助每周答题开始无法执行下去

### ISSUE THREAD

**Issue by zz33600606** [power-helper/power-helper-backup20210704#112]
开始每日答题……
每日答题之前学完了
开始每周答题……

DevTools listening on ws://127.0.0.1:57823/devtools/browser/29f39c1e-09e0-486d-9d5d-a231e2c08187
请保持窗口最大化
请保持窗口最大化
请保持窗口最大化
本月
2021年5月第三周答题
已作答+5积分
重新答题
2021年5月第二周答题
已作答+5积分
重新答题
2021年5月第一周答题
已作答+5积分
重新答题
没有可点击的【查看提示】按钮
Traceback (most recent call last):
  File "pandalearning.py", line 99, in <module>
  File "pdlearn\answer_question.py", line 243, in weekly
ValueError: not enough values to unpack (expected 2, got 0)
[4680] Failed to execute script pandalearning

请问一下这是什么问题 我是上上个版本的，这次换了主程序，然后加了一下path
但是teletram群不知道怎么登，下不来完整版

**Comment by whizzliang** [comment]
您的path dll文件是从哪里下的呢，我找了很多个，都不能用，我win7~

**Comment by zz33600606** [comment]
我就是用的原来的

**Comment by TCPsoftware** [comment]
上个提交遗留下来的问题 🤔
新提交中将 return "" 改为了 return [],"" ，返回两个结果，不至于语法报错
