### ISSUE TITLE
v20210521版本有木马风险

### ISSUE THREAD

**Issue by wangquansh** [power-helper/power-helper-backup20210704#119]
![image](https://user-images.githubusercontent.com/10202624/119587109-955b5400-be00-11eb-8421-af7d51947ced.png)

原始地址下载不了，提供的地址下载后，杀毒软件报有木马，对比之前的软件发现没有这个现场，请核查下软件来源提供者。

**Comment by LevineWoo** [comment]
不放心那就用源码呗。

**Comment by thinkrecord** [comment]
https://github.com/TechXueXi/TechXueXi/issues/6
