### ISSUE TITLE
缺失api-ms-win-core-path-l1-1-0.dll 

### ISSUE THREAD

**Issue by chencxm520** [power-helper/power-helper-backup20210704#125]
![image](https://user-images.githubusercontent.com/65608489/120098811-8eb73e80-c16a-11eb-907e-140056415cea.png)
缺失api-ms-win-core-path-l1-1-0.dll 不知道该装VC那个版本？

**Comment by whizzliang** [comment]
我一样遇到了这个问题，完全不懂，不知道怎样解决

**Comment by mudapi** [comment]
自己编译的没有这个问题，百度是说重装2015版本，但是我试过没用

**Comment by thinkrecord** [comment]
win平台可能提示`无法定位程序输入点ucrtbase.terminate于动态链接库api-ms-win-crt-runtime-|1-1-0.dll`等缺失dll文件的问题而无法使用，尝试安装`Visual C++ Redistributable for Visual Studio 2015`

下载安装Visual C++ Redistributable for Visual Studio 2015:

[VC REDIST X64![](https://img.shields.io/badge/download-vc_redist.x64-blue.svg?style=for-the-badge&logo=visualstudiocode)](https://raw.fastgit.org/TechXueXi/Panda-Learning/master/windows不能运行时安装/vc_redist.x64.exe) 

[VC REDISTX32![](https://img.shields.io/badge/download-vc_redist.x86-blue.svg?style=for-the-badge&logo=visualstudiocode)](https://raw.fastgit.org/TechXueXi/Panda-Learning/master/windows不能运行时安装/vc_redist.x86.exe)
