### ISSUE TITLE
自否添加自动翻页？

### ISSUE THREAD

**Issue by yangyang0133** [power-helper/power-helper-backup20210704#134]
**系统版本，包含位数**：win10 X64

**python版本**：3.9.5

**软件/源码版本**：V20210521

**浏览器、驱动版本**： 91.0.4472.77

-----

## 详细描述
答：每周答题和专项答题，如果第一页全部答完，不能自动翻页，能否添加？

## 全部报错
答：

## 建议
答：能否加个自动翻页？

**Comment by TCPsoftware** [comment]
将加入

**Comment by TCPsoftware** [comment]
已加入

**Comment by yangyang0133** [comment]
> 已加入

dev 分支么？

**Comment by TCPsoftware** [comment]
> > 已加入
> 
> dev 分支么？

是的
