### ISSUE TITLE
使用方法分享

### ISSUE THREAD

**Issue by YeQiuO** [power-helper/power-helper-backup20210704#135]
看到大佬们辛苦打代码，大家却老是发用不了的 issue
特此总结一下我遇到的问题和解决方法 希望能帮助大家好好利用这些代码

放一个可以直接使用的链接 
bat 文件中的两条路径修改一下就可以直接用bat文件打开源码了
bat 做一个快捷键放菜单栏 和exe文件差不多方便啦
链接：https://pan.baidu.com/s/1vt1xbvwBj_G9_UsHbz3VBQ 
提取码：1111 

1、遇到的大多数问题都是 chrome 版本问题，里面放了 73.0 的基本上不会出问题
2、以后更新只需要把源码替换一下就可以了

salute 大佬们的无私精神
希望我也能帮助到你！百度网盘可能比较慢，但我找不到更好的方法了....

**Comment by around999** [comment]
小白求教：Anaconda装了，两个bat路径也修改了，运行xxqg.bat闪退

**Comment by YeQiuO** [comment]
> 小白求教：Anaconda装了，两个bat路径也修改了，运行xxqg.bat闪退

anaconda 里面的环境要配置哦
把 import 的都配一下

**Comment by around999** [comment]
> > 小白求教：Anaconda装了，两个bat路径也修改了，运行xxqg.bat闪退
> 
> anaconda 里面的环境要配置哦
> 把 import 的都配一下

只是根据https://blog.csdn.net/wangjie36/article/details/107299189/和https://blog.csdn.net/yelly0/article/details/88426076安装了Anaconda而已，请教环境配置要如何配置，从未接触过python之类，能否发个教详细的教程链接供参考研究

**Comment by AW404** [comment]
感谢。打包exe下载https://wws.lanzoui.com/iAL64pzdwza
