### ISSUE TITLE
可以出个docker-compose的版本吗？

### ISSUE THREAD

**Issue by qq34347476** [power-helper/power-helper-backup20210704#136]
**系统版本，包含位数**：

**python版本**：

**软件/源码版本**：

**浏览器、驱动版本**：

-----

## 详细描述
答：

## 全部报错
答：

## 建议
答：

**Comment by TCPsoftware** [comment]
可能有几方面的问题：
headless chrome不一定能找到元素并操作
二维码发送扫描问题
保活
接1，如果不使用headless chrome则需要GUI

**Comment by wx5223** [comment]
建议可以参考：
https://github.com/TechXueXi/TechXueXi/tree/dev-headless-single-docker
