### ISSUE TITLE
docker版在钉钉发送的卡片无法打开

### ISSUE THREAD

**Issue by zlhdd108** [power-helper/power-helper-backup20210704#143]
**系统版本，包含位数**：
Android 11 ；三星one UI 3.1
**python版本**：

**软件/源码版本**：

**浏览器、驱动版本**：

-----

## 详细描述
答：已经收到钉钉bot的推送，605和616的image都已经试过了，钉钉bot可以收到推送卡片，但是点了没反应，没办法拉起app

## 全部报错
答：

## 建议
答：

**Comment by bleehome** [comment]
发送的其实是个字符串，类似于下面的：
unsafe:data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAANIAAADSCAYAAAA/mZ5CAAAUZklEQVR4Xu3d4ZoauQ4E0...  后面还有很长很长

把这个字符串复制下来，把前面的   unsafe:  去掉，只保留从  data:image/ 开始到最后的字符串，复制到现代浏览器里就能看到二维码了=

**Comment by wx5223** [comment]
使用616版本的镜像会额外推送一个链接，复制链接到学习强国app中发给自己，点击打开发送的链接就可以登录了。
616版本镜像使用说明请参考：
https://github.com/TechXueXi/TechXueXi/tree/dev-headless-single-docker
