### ISSUE TITLE
钉钉收到的链接点击后跳转不正常

### ISSUE THREAD

**Issue by zhaozhiming** [power-helper/power-helper-backup20210704#150]
最新docker版本的发送到钉钉的链接，点击后会跳转到[下载页面](https://h5.xuexi.cn/page/download.html)，并没有显示二维码。

比如我的钉钉收到的链接地址是：https://login.xuexi.cn/login/qrcommit?showmenu=false&code=qr:547DBA94-5351-4BA0-A139-03D773DF0D1C&appId=dingoankubyrfkttorhpou

我在钉钉点击这个地址后，浏览器就重定向到：https://h5.xuexi.cn/page/download.html

导致无法扫码登陆，请帮忙看看，谢谢

**Comment by oldunclez** [comment]
看这个  https://github.com/TechXueXi/TechXueXi/issues/147

**Comment by zhaozhiming** [comment]
可以了，感谢
