### ISSUE TITLE
文章学习正常，视频学习积分无法获得，时长和观看数量都为0，循环进行视频学习。

### ISSUE THREAD

**Issue by 9UW** [power-helper/power-helper-backup20210704#16]
![image](https://user-images.githubusercontent.com/65102267/82723753-d4ddf480-9d03-11ea-85f2-b2a862230cd5.png)
和以前老版的Panda某Bug有类似之处，有大佬能否给出修复。Debug.log错误代码如下
```
[0523/xxxxxxx.xxx:ERROR:process_reader_win.cc(123)] NtOpenThread: {无法访问} 过程已请求访问一对象，但未给访问权限。 (0xc0000022)
[0523/xxxxxxx.xxx:ERROR:exception_snapshot_win.cc(98)] thread ID 1432 not found in process
```

**Comment by thinkrecord** [comment]
查找了一下资料，应该是权限问题，可以尝试对启动文件 右键管理员身份运行 或 属性兼容性改为win7、xp ；
修改/chrome/chrome.exe文件权限
上下调整一下这两个文件的权限试试。
另外可以试一下能否使用/chrome/chrome.exe打开xuexi视频正常观看
代码中应该已对此优化，我有空再看看。
可以参考：
https://stackoverflow.com/questions/48811713/c-sharp-selenium-chromedriver-google-chrome-fails-when-run-as-administrator

**Comment by shajia1992** [comment]
> ![image](https://user-images.githubusercontent.com/65102267/82723753-d4ddf480-9d03-11ea-85f2-b2a862230cd5.png)
> 和以前老版的Panda某Bug有类似之处，有大佬能否给出修复。Debug.log错误代码如下
> 
> ```
> [0523/xxxxxxx.xxx:ERROR:process_reader_win.cc(123)] NtOpenThread: {无法访问} 过程已请求访问一对象，但未给访问权限。 (0xc0000022)
> [0523/xxxxxxx.xxx:ERROR:exception_snapshot_win.cc(98)] thread ID 1432 not found in process
> ```

确实遇到这个问题了，但我当时还以为是单位的网络慢，因为单位的网络确实比较慢，后来我在家又弄了一下就把视频都刷完了

**Comment by shajia1992** [comment]
> 查找了一下资料，应该是权限问题，可以尝试对启动文件 右键管理员身份运行 或 属性兼容性改为win7、xp ；
> 修改/chrome/chrome.exe文件权限
> 上下调整一下这两个文件的权限试试。
> 另外可以试一下能否使用/chrome/chrome.exe打开xuexi视频正常观看
> 代码中应该已对此优化，我有空再看看。
> 可以参考：
> https://stackoverflow.com/questions/48811713/c-sharp-selenium-chromedriver-google-chrome-fails-when-run-as-administrator

确实遇到这个问题了，但我当时还以为是单位的网络慢，因为单位的网络确实比较慢，后来我在家又弄了一下就把视频都刷完了

**Comment by hpzka** [comment]
> > ![image](https://user-images.githubusercontent.com/65102267/82723753-d4ddf480-9d03-11ea-85f2-b2a862230cd5.png)
> > 和以前老版的Panda某Bug有类似之处，有大佬能否给出修复。Debug.log错误代码如下
> > ```
> > [0523/xxxxxxx.xxx:ERROR:process_reader_win.cc(123)] NtOpenThread: {无法访问} 过程已请求访问一对象，但未给访问权限。 (0xc0000022)
> > [0523/xxxxxxx.xxx:ERROR:exception_snapshot_win.cc(98)] thread ID 1432 not found in process
> > ```
> 
> 确实遇到这个问题了，但我当时还以为是单位的网络慢，因为单位的网络确实比较慢，后来我在家又弄了一下就把视频都刷完了

那是如何解决了，最后如何解决了

**Comment by 9UW** [comment]
> > > ![image](https://user-images.githubusercontent.com/65102267/82723753-d4ddf480-9d03-11ea-85f2-b2a862230cd5.png)
> > > 和以前老版的Panda某Bug有类似之处，有大佬能否给出修复。Debug.log错误代码如下
> > > ```
> > > [0523/xxxxxxx.xxx:ERROR:process_reader_win.cc(123)] NtOpenThread: {无法访问} 过程已请求访问一对象，但未给访问权限。 (0xc0000022)
> > > [0523/xxxxxxx.xxx:ERROR:exception_snapshot_win.cc(98)] thread ID 1432 not found in process
> > > ```
> > 
> > 
> > 确实遇到这个问题了，但我当时还以为是单位的网络慢，因为单位的网络确实比较慢，后来我在家又弄了一下就把视频都刷完了
> 
> 那是如何解决了，最后如何解决了

我试了一下，删去原来文件，重新下载后，运行新下载的程序就恢复正常，很迷。

**Comment by 9UW** [comment]
> 查找了一下资料，应该是权限问题，可以尝试对启动文件 右键管理员身份运行 或 属性兼容性改为win7、xp ；
> 修改/chrome/chrome.exe文件权限
> 上下调整一下这两个文件的权限试试。
> 另外可以试一下能否使用/chrome/chrome.exe打开xuexi视频正常观看
> 代码中应该已对此优化，我有空再看看。
> 可以参考：
> https://stackoverflow.com/questions/48811713/c-sharp-selenium-chromedriver-google-chrome-fails-when-run-as-administrator

因删除了原先文件，重新下载程序，运行正常，之前的Bug不再重复，从而无法给出有效反馈。
现发现Debug.log中错误代码是因为一直循环播放没有意义，自己强行结束命令行导致的，而貌似非循环视频播放本身的Bug。
