### ISSUE TITLE
老哥，之前的用钉钉登陆并且保存好，比较方便，不用每次扫码，还有办法改回以前那样么，是官方限制不可逆的吗，老哥

### ISSUE THREAD

**Issue by shajia1992** [power-helper/power-helper-backup20210704#17]
老哥，之前的用钉钉登陆并且保存好，比较方便，不用每次扫码，还有办法改回以前那样么，是官方限制不可逆的吗，老哥

**Comment by hpzka** [comment]
> 老哥，之前的用钉钉登陆并且保存好，比较方便，不用每次扫码，还有办法改回以前那样么，是官方限制不可逆的吗，老哥

我是直接墙菓app扫码登录

**Comment by shajia1992** [comment]
> > 老哥，之前的用钉钉登陆并且保存好，比较方便，不用每次扫码，还有办法改回以前那样么，是官方限制不可逆的吗，老哥
> 
> 我是直接墙菓app扫码登录

我也是一直用的扫码

**Comment by thinkrecord** [comment]
本软件是使用xuexi的PC网站。

而现在xuexi网站只支持扫码登陆

还是扫码登陆稳定一些。
