### ISSUE TITLE
如何修改为：阅读文章X/12,观看视频X/12,文章时长：X/12;视频时长：X/12

### ISSUE THREAD

**Issue by solife2020** [power-helper/power-helper-backup20210704#18]

**Comment by thinkrecord** [comment]
修改`TechXueXi/Source Packages/pandalearning.py `对应位置即可

**Comment by solife2020** [comment]
比如每天我想自动看文章12，观看视频12，文章时长这些都设置增加一倍，怎么修改呢？

**Comment by thinkrecord** [comment]
这个可以增加，但是分数不会增加了。如果确有需要，应该要大改，可以尝试找含each[x]的`比较运算表达式`修改，这个是存各项分值的，源码是达到分停止，可修改为运行12次。也可源码运行完后再加次数：
如：
![image](https://user-images.githubusercontent.com/63346301/83702624-cbc42000-a63f-11ea-9a84-ac7694c2b0a4.png)

![image](https://user-images.githubusercontent.com/63346301/83702689-f4e4b080-a63f-11ea-8849-3c63d761b531.png)

**Comment by thinkrecord** [comment]
加分的话网页限制25分/天，没办法，可换用对电脑性能要求高，配置十分复杂的但37-42分/天同类产品：https://github.com/TechXueXi/AutoXue
这个是从app入手，支持答题

**Comment by solife2020** [comment]
因为点点通每天需要额外增加6个文章和6个视频，才能获得满分33分。
