### ISSUE TITLE
有被封号的吗？

### ISSUE THREAD

**Issue by fuzhiyong2** [power-helper/power-helper-backup20210704#19]
**系统版本，包含位数**：

**python版本**：

**软件/源码版本**：

**浏览器、驱动版本**：

-----

## 详细描述
答：

## 全部报错
答：

## 建议
答：

**Comment by thinkrecord** [comment]
#10

**Comment by thinkrecord** [comment]
注意尽量使用自用电脑，最好不要使用vps,云主机等。只是自用，一般不会封
