### ISSUE TITLE
请问现在阅读文章和视频的时间是在一定范围内随机的吗？不是的话可不可以增加一个这样的功能呢？感觉每次时间一样的话容易被检测。亲测文章和视频只要够7-8s就算一次加分了。

### ISSUE THREAD

**Issue by github10954** [power-helper/power-helper-backup20210704#20]
**系统版本，包含位数**：

**python版本**：

**软件/源码版本**：

**浏览器、驱动版本**：

-----

## 详细描述
答：

## 全部报错
答：

## 建议
答：

**Comment by thinkrecord** [comment]
之前就是(5, 15)随机

**Comment by github10954** [comment]
我今天特意看了下，显示的文章都是从120s，视频都是从180s开始倒计时的。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"tobctobc"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月9日(星期二) 下午4:32
收件人:&nbsp;"TechXueXi/TechXueXi"<TechXueXi@noreply.github.com&gt;;
抄送:&nbsp;"•"<596972884@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TechXueXi/TechXueXi] 请问现在阅读文章和视频的时间是在一定范围内随机的吗？不是的话可不可以增加一个这样的功能呢？感觉每次时间一样的话容易被检测。亲测文章和视频只要够7-8s就算一次加分了。 (#20)





 
(5, 15)随机

**Comment by thinkrecord** [comment]
就是说，一篇文章不需要(5, 15)+120s?

**Comment by github10954** [comment]
因为每次只显示了120和180，我以为是固定的实际有加上随机的话就没问题了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"tobctobc"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月9日(星期二) 下午4:52
收件人:&nbsp;"TechXueXi/TechXueXi"<TechXueXi@noreply.github.com&gt;;
抄送:&nbsp;"•"<596972884@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TechXueXi/TechXueXi] 请问现在阅读文章和视频的时间是在一定范围内随机的吗？不是的话可不可以增加一个这样的功能呢？感觉每次时间一样的话容易被检测。亲测文章和视频只要够7-8s就算一次加分了。 (#20)





 
就是说，一篇文章不需要(5, 15)+120s?
