### ISSUE TITLE
从叮叮无法登陆了

### ISSUE THREAD

**Issue by forbbs** [power-helper/power-helper-backup20210704#21]
**系统版本，包含位数**：64位win8

**python版本**：python 3.7.3

**软件/源码版本**：最新版

**浏览器、驱动版本**：ie11

-----

## 详细描述
答：叮叮界面登陆，输入验证码，点登陆后，弹出来一个callback.json文件，保存后，这个文件里内容是
“{"code":404,"message":"接口 [/open/api/sns/callback] 不存在","ok":false}”

## 全部报错
答：无法登陆。刷二维码可以登录。

## 建议
答：原来的叮叮登陆网址应该是被官方改过了

**Comment by thinkrecord** [comment]
现在xuexi网站官方只支持扫码登陆。网页端没有办法。
