### ISSUE TITLE
求上传最新的代码

### ISSUE THREAD

**Issue by gulshj** [power-helper/power-helper-backup20210704#23]
**系统版本，包含位数**：

**python版本**：

**软件/源码版本**：

**浏览器、驱动版本**：

-----

## 详细描述
答：求上传最新的代码，现在的代码还是输入账号密码，不是最新版的扫二维码，想改一下学习过程，无奈登录这块办不了。

**Comment by thinkrecord** [comment]
上传这么久，终于有人发现 源码 和 Releases 对不上了

**Comment by thinkrecord** [comment]
。
