### ISSUE TITLE
专项答题 无法交卷 win10 64位系统

### ISSUE THREAD

**Issue by mikeshmily** [power-helper/power-helper-backup20210704#28]
**系统版本，包含位数**：

**python版本**：

**软件/源码版本**：

**浏览器、驱动版本**：

-----

## 详细描述
答：

## 全部报错
答：

## 建议
答：

**Comment by thinkrecord** [comment]
这个，我们正在尝试解决

**Comment by thinkrecord** [comment]
解决了
