### ISSUE TITLE
专项答题答题完毕后卡住

### ISSUE THREAD

**Issue by xinyu-io** [power-helper/power-helper-backup20210704#31]
**系统版本，包含位数**：
MacOS10.15.6

**python版本**：
python3

**软件/源码版本**：
latest

**浏览器、驱动版本**：

chrome 版本 86.0.4229.0（正式版本）dev (x86_64)

-----

## 详细描述
答：专项答题卡住了，答完之后没有退出
应该是代码 563 行这里的判断有问题了。
```python
            if each[6] >= 5:
                print("检测到专项答题分数已满,退出学习")
                driver_zhuanxiang.quit()
```

**Comment by thinkrecord** [comment]
现在要自己点交卷。

**Comment by thinkrecord** [comment]
https://github.com/TechXueXi/TechXueXi/issues/28
