### ISSUE TITLE
安装包无法与服务器建立连接 Error sending request 安装失败 链接服务失败

### ISSUE THREAD

**Issue by xindi98** [power-helper/power-helper-backup20210704#32]

**Comment by xindi98** [comment]
![4371caf27209557bc07e24d73d9ba33](https://user-images.githubusercontent.com/35103804/93579219-cf05d080-f9d0-11ea-8e01-7c1257a1374c.png)

**Comment by thinkrecord** [comment]
用了一个较稳定的国内 github raw cdn 加速。

有问题就手动下载老用户单文件替换旧版本 TechXueXi.exe 后使用
