### ISSUE TITLE
视频内容陷入循环

### ISSUE THREAD

**Issue by xinyu-io** [power-helper/power-helper-backup20210704#34]
视频内容陷入循环
```
有可点击的【查看提示】按钮
获取提示： []
等待  3  秒
本题没有提示
没有找到提示，暂时略过
填空题
有可点击的【查看提示】按钮
获取提示： []
等待  5  秒
本题没有提示
没有找到提示，暂时略过
填空题
有可点击的【查看提示】按钮
获取提示： []
等待  4  秒
本题没有提示
没有找到提示，暂时略过
填空题
有可点击的【查看提示】按钮
获取提示： []
等待  3  秒
本题没有提示
没有找到提示，暂时略过
填空题
有可点击的【查看提示】按钮
获取提示： []
等待  3  秒
本题没有提示
没有找到提示，暂时略过
填空题
没有可点击的【查看提示】按钮
等待  3  秒
```

![image](https://user-images.githubusercontent.com/32320149/93669271-aa3f5500-fac5-11ea-94f8-734da2449a55.png)

**Comment by xinyu-io** [comment]
目前主要遇到三处问题：
1. 专项要手动点交卷。
2. 视频题目循环卡住。
3. 源码太大了，.git 文件里的。

**Comment by thinkrecord** [comment]
专项要手动点交卷。解决了
视频题目循环卡住。计划搜索答案，近期不会解决，所以要值守
源码太大了，.git 文件里的。 从 https://github.com/TechXueXi/TechXueXi/releases 下源码，或使用 代理，gitee ，镜像 加速

**Comment by xinyu-io** [comment]
视频题目，好像就是每日答题最后一个，暂时给个随机答案跳过就好了。
或者做个检测，检测到有视频就随意乱答就好了。。。
