### ISSUE TITLE
专项答题最后一题无法提交

### ISSUE THREAD

**Issue by kurokosan98** [power-helper/power-helper-backup20210704#35]
**系统版本，包含位数**：Windows7 x64

**软件/源码版本**：20200919

## 详细描述
答：专项答题

## 全部报错
答：  最后一题无法提交
![image](https://user-images.githubusercontent.com/28686375/93727481-ec63b600-fbed-11ea-98a3-04e556bb7a5a.png)
一直重复打开提示关闭提示,最后一题

## 建议
答：检查最后一题

**Comment by thinkrecord** [comment]
是的，所以要人工值守

**Comment by thinkrecord** [comment]
解决了
