### ISSUE TITLE
争上游答题以及双人对战问题

### ISSUE THREAD

**Issue by DoveBoy** [power-helper/power-helper-backup20210704#38]
**系统版本，包含位数**：64

**python版本**：3.8.5

**软件/源码版本**：20200928

**浏览器、驱动版本**：

-----

## 详细描述
答：目前最新版9.28的新增了争上游答题以及双人对战，请问能否增加这两个功能？

## 全部报错
答：

## 建议
答：

**Comment by thinkrecord** [comment]
xuexi.cn 网页有这个功能吗？

**Comment by Halloworld245** [comment]
这样做就很不道德了, 对机器不对人啊

**Comment by zhumaoyulanlan** [comment]
主要网页版没有这功能
