### ISSUE TITLE
20200928版使用源码运行在Python3.9.0环境下报错

### ISSUE THREAD

**Issue by DoveBoy** [power-helper/power-helper-backup20210704#39]
**系统版本，包含位数**：64

**python版本**：3.9.0

**软件/源码版本**：20200928

**浏览器、驱动版本**：

-----

## 详细描述
答：正常运行源码后出现扫描二维码登录的界面，确认登录后就会报错，然后脚本就会自动闪退关闭

## 全部报错
答：

## 建议
答：

![image](https://user-images.githubusercontent.com/19201447/95410151-c06a6380-0955-11eb-8db2-f20f3a23a6f1.png)

**Comment by thinkrecord** [comment]
我运行正常，现在工作很多，请自行百度、谷歌解决吧

**Comment by DoveBoy** [comment]
> 我运行正常，现在工作很多，请自行百度、谷歌解决吧

百度不到才来问的，至少说下办法吧？

**Comment by thinkrecord** [comment]
不知道。我也只能搜索，以最后一行报错为主，多换几个关键词试试

**Comment by DoveBoy** [comment]
> 不知道。我也只能搜索，以最后一行报错为主，多换几个关键词试试

手动删除所有文件下包含encoding的字段后，虽然运行不报错了，但是没法使用，每日答题就没法用

**Comment by qileilu** [comment]
遇到相同问题，修改“/SourcePackages/pdlearn/score.py"
第13行和第17行，删掉：    ` , encoding="utf8"`
可正常运行。

**Comment by DoveBoy** [comment]
> 遇到相同问题，修改“/SourcePackages/pdlearn/score.py"
> 第13行和第17行，删掉： ` , encoding="utf8"`
> 可正常运行。

很早试过这样可以执行，但是无法答题了

**Comment by qileilu** [comment]
我的正常
Python 3.9.0 (default, Oct  7 2020, 23:09:01) 
[GCC 10.2.0] on linux

**Comment by DoveBoy** [comment]
> 我的正常
> Python 3.9.0 (default, Oct 7 2020, 23:09:01)
> [GCC 10.2.0] on linux

我再试试吧，我现在是Python3.9.1

**Comment by DoveBoy** [comment]
> 我的正常
> Python 3.9.0 (default, Oct 7 2020, 23:09:01)
> [GCC 10.2.0] on linux

看运行结果只知道可能需要删除`, encoding="utf8"`，一开始的操作是删除pandalearning.py和score.py文件下所有包含`, encoding="utf8"`的字段，能运行不报错但是不能答题。现在只删除score.py下的字段正常了，感谢大佬解答

**Comment by nickhelion** [comment]
从 Python 3.1 版本开始，`json.loads()`中的`encoding` 参数就已经废弃并被忽视了。3.9 版本只是抛错而已，理论上全部去除也是可以的。

https://bugs.python.org/issue39377

#56 提交了一个修复。

请问开发团队的 Python 版本是多少，是否可以在文档中注明，以便我们参与时可以统一开发环境？

**Comment by thinkrecord** [comment]
> 从 Python 3.1 版本开始，`json.loads()`中的`encoding` 参数就已经废弃并被忽视了。3.9 版本只是抛错而已，理论上全部去除也是可以的。
> 
> https://bugs.python.org/issue39377
> 
> #56 提交了一个修复。
> 
> 请问开发团队的 Python 版本是多少，是否可以在文档中注明，以便我们参与时可以统一开发环境？

@czy1996 目前我使用的版本是 3.8.3 。您现在无需更改现在使用的版本。我会过段时间开始着手优化项目并统一这些细节
