### ISSUE TITLE
./user 创建失败

### ISSUE THREAD

**Issue by opencode200** [power-helper/power-helper-backup20210704#40]
**系统版本，包含位数**：windows10 64

**python版本**：

**软件/源码版本**：v20200928

**浏览器、驱动版本**：

-----

## 详细描述
答：启动报错，信息如下
```
Traceback (most recent call last):
     File "pandalearning.py", line 611, in <module>
     File "pdlearn\user.py", line 14, in get_user
     File "os.py", line 213, in makedirs
     File  "os.py", line 223, in makedirs
PermissionError: [WinError 5] 拒绝访问。 ： "./user"
[3584] Failed to executor script pandalearning
```

# 重现步骤：
安装Windows完整版，采用默认安装路径。第一次运行打开程序，登录，选择一个模式

## 建议
答：应该是安装路径下，某些目录需要管理员权限才能新建文件夹，当以普通用户运行时，无新建user文件夹权限，所以报错。建议在windows下默认目录采用USERPROFILE目录，*unix下采用HOME目录，代码如下

```
USER_DIR = os.getenv('USERPROFILE' if os.name == 'nt' else 'HOME', os.getcwd())
WORK_PROFILE_DIR = os.poth.join(USER_DIR, '.techxuexi')
USER_PROFILE_DIR = os.poth.join(WORK_PROFILE_DIR, 'user')
```

**Comment by thinkrecord** [comment]
> 某些目录需要管理员权限才能新建文件夹

是的。目前自动打包不完善。安装，指定目录不方便手动清除垃圾文件。

**Comment by TCPsoftware** [comment]
有可能是运行命令行的目录在高权限目录，与程序目录不同，在代码中创建文件时路径改为程序的目录可避免（但是程序本身不要放在高权限目录）
