### ISSUE TITLE
windows10 无法运行

### ISSUE THREAD

**Issue by fatfish516** [power-helper/power-helper-backup20210704#51]
**系统版本，包含位数**：

**python版本**：

**软件/源码版本**：

**浏览器、驱动版本**：

-----

## 详细描述
答：Chrome已经安装，但是还是无法运行软件，软件下载的是完整版，在一开始弹出的命令行输入数字选择模式之后呢，报错然后闪退了。。。。。

## 全部报错
答：
![image](https://user-images.githubusercontent.com/38204048/101452378-94288e80-3968-11eb-95b4-2033fc502d2b.png)

## 建议
答：

**Comment by drw2005** [comment]
今天也碰到这个问题，是什么原因啊，哪位大佬给指点指点。

**Comment by TCPsoftware** [comment]
请更新新版再次尝试，如仍有问题请重新开启此issue
