### ISSUE TITLE
64位WIN7下运行提示Mydriver初始化失败，很多人碰到这个问题，有大佬解决的进来指导指导。。。

### ISSUE THREAD

**Issue by drw2005** [power-helper/power-helper-backup20210704#64]
**系统版本，包含位数**：64位WIN7

**python版本**：3.8

**软件/源码版本**：v20200928

**浏览器、驱动版本**：

-----

## 详细描述
答：Mydriver初始化失败

## 全部报错
答：闪退

## 建议
答：

**Comment by zhaojie199512** [comment]
64位win7下打开学习强国exe文件就黑框闪一下就没了。。。。。。
解决了：是 win7 不支持python 3.8.6,需要升级win7 到sp1 版本并安装其他几个补丁才行（网上搜win7 sp1 补丁包）就可以运行了。建议下载补丁包合集，不只是要装升级sp1的补丁还有其他补丁，所有补丁装完程序就可以用了，所有功能都支持。因为直接安装python会提示至少要sp1版本和其他应用才能安装，所以才想到估计是这个问题。

**Comment by drw2005** [comment]
> 64位win7下打开学习强国exe文件就黑框闪一下就没了。。。。。。
> 解决了：是 win7 不支持python 3.8.6,需要升级win7 到sp1 版本并安装其他几个补丁才行（网上搜win7 sp1 补丁包）就可以运行了。建议下载补丁包合集，不只是要装升级sp1的补丁还有其他补丁，所有补丁装完程序就可以用了，所有功能都支持。因为直接安装python会提示至少要sp1版本和其他应用才能安装，所以才想到估计是这个问题。

我的WIN7已经安装有sp1和其他补丁，安装的python是3.8.6版本。

**Comment by zhaojie199512** [comment]
> > 64位win7下打开学习强国exe文件就黑框闪一下就没了。。。。。。
> > 解决了：是 win7 不支持python 3.8.6,需要升级win7 到sp1 版本并安装其他几个补丁才行（网上搜win7 sp1 补丁包）就可以运行了。建议下载补丁包合集，不只是要装升级sp1的补丁还有其他补丁，所有补丁装完程序就可以用了，所有功能都支持。因为直接安装python会提示至少要sp1版本和其他应用才能安装，所以才想到估计是这个问题。
> 
> 我的WIN7已经安装有sp1和其他补丁，安装的python是3.8.6版本。

那你可能是其他问题导致的，我当时闪屏一瞬间用手机抓拍的报错代码如下图所示，好像不是你啊那个
![IMG_20210130_153257](https://user-images.githubusercontent.com/12878073/106358812-70227180-6349-11eb-9ca9-aec3ae469a16.jpg)

**Comment by drw2005** [comment]
> > > 64位win7下打开学习强国exe文件就黑框闪一下就没了。。。。。。
> > > 解决了：是 win7 不支持python 3.8.6,需要升级win7 到sp1 版本并安装其他几个补丁才行（网上搜win7 sp1 补丁包）就可以运行了。建议下载补丁包合集，不只是要装升级sp1的补丁还有其他补丁，所有补丁装完程序就可以用了，所有功能都支持。因为直接安装python会提示至少要sp1版本和其他应用才能安装，所以才想到估计是这个问题。
> > 
> > 
> > 我的WIN7已经安装有sp1和其他补丁，安装的python是3.8.6版本。
> 
> 那你可能是其他问题导致的，我当时闪屏一瞬间用手机抓拍的报错代码如下图所示，好像不是你啊那个
> ![IMG_20210130_153257](https://user-images.githubusercontent.com/12878073/106358812-70227180-6349-11eb-9ca9-aec3ae469a16.jpg)

确实和你的报错不一样，我的是报Mydriver初始化失败。报这个错的好像有很多人，win7、win10都有。我翻遍了问题也没找到有人能解决这个问题。

**Comment by wbyiml** [comment]
我也出现这种情况，已解决。
我的系统：windows 10
原因：缺少chromedriver
解决办法：
浏览器中输入chrome://version/
![image](https://user-images.githubusercontent.com/35860239/118091167-19730c00-b3fd-11eb-9087-412b8d0c76be.png)
在https://npm.taobao.org/mirrors/chromedriver/找到相应版本并下载
![image](https://user-images.githubusercontent.com/35860239/118091288-31e32680-b3fd-11eb-8817-6198025a89c6.png)
在项目SourcePackages下创建chrome文件夹并把下载的chromedriver解压到该文件夹下即可
![image](https://user-images.githubusercontent.com/35860239/118091332-43c4c980-b3fd-11eb-96a4-0a7f7a95a6ff.png)
