### ISSUE TITLE
Failed to excute script pandalearning.

### ISSUE THREAD

**Issue by GHOSTagw** [power-helper/power-helper-backup20210704#65]
**系统版本，包含位数**：Windows 7 SP1 x64

**软件/源码版本**：v20200928完整版

-----

## 详细描述
答：Windows 7 之前使用正常，后来不知道怎么回事就报错了，然后就一直不能用了，期间也没有进行什么系统升级。
（可能是因为APP更新了？）

## 全部报错
答：
![图片](https://user-images.githubusercontent.com/40930046/107599806-c2726500-6c5c-11eb-9c60-ce1755b1d3dc.png)

**Comment by TCPsoftware** [comment]
新版本删除了get_v_log函数

**Comment by drw2005** [comment]
和楼主同样情况，win7下始终出错。win10就正常。

**Comment by Notjava** [comment]
WIN10也报错

**Comment by TCPsoftware** [comment]
版本更新了，相关函数已弃用。试试新版本有无此问题
