### ISSUE TITLE
登录账号后,提示无法进行视频观看和答题,打开的网页是正在维护中

### ISSUE THREAD

**Issue by FlynnClaudia** [power-helper/power-helper-backup20210704#78]
**系统版本，包含位数**：win10 20H2

**python版本**：

**软件/源码版本**：20210316

**浏览器、驱动版本**：chrome 90.0.4430.72

-----

![image](https://user-images.githubusercontent.com/67038632/115109579-3d336580-9fa9-11eb-84fa-ba4d6347c171.png)

**Comment by shq1234** [comment]
找到mydriver.py文件找到setcookie方法在for循环之前加一行代码 cookies = self.get_cookies();具体图片如下
![image](https://user-images.githubusercontent.com/49202460/115427909-75020d80-a234-11eb-9e4a-acacee0cb595.png)

**Comment by hancj0528** [comment]
同样的问题 chrome89就没问题

**Comment by SuperManito** [comment]
+1，mac用89版chrome脚本报错让换成90版，升级以后无法获取用户ID，视频学习显示系统正在维护，脚本报错终止，希望作者能修复🙏

**Comment by WenuYang** [comment]
更换89版本的Chrome。
1、卸载windows上的chrome
2、下载89版本的Chrome并安装，然后将原来的90版本的chromdriver.exe删掉，更换为89版本的
3、运行脚本即可

**Comment by OliverYmy** [comment]
这个问题出现的原因是什么呢？开发组请解决下呗/(ㄒoㄒ)/~~

**Comment by mattwong05** [comment]
同样的问题！

**Comment by mattwong05** [comment]
稍作修改，解决了问题，希望可以帮到大家。
本人也是90版本的Chrome浏览器，遇到了同样问题，稍作修改，已在本地解决并成功运行，已提交了Pull Request，[详见链接](https://github.com/TechXueXi/TechXueXi/pull/88)
@OliverYmy @hancj0528 @FlynnClaudia

**Comment by OliverYmy** [comment]
@WANGJUNHAOmatt 感谢，我查到那个cookie新特性了，但不知道mydriver.py该怎么改orz

**Comment by mattwong05** [comment]
@OliverYmy
> @WANGJUNHAOmatt 感谢，我查到那个cookie新特性了，但不知道mydriver.py该怎么改orz

客气啦，很期待可以帮到你，我已经提交了Pull Requests
请点击链接查看->[https://github.com/TechXueXi/TechXueXi/pull/88](https://github.com/TechXueXi/TechXueXi/pull/88)

或者可以直接修改 mydriver.py 中131行左右的 `set_cookies()` 函数为如下：
``` python
def set_cookies(self, cookies):
    try:
        # 解决Chrome 90版本无法运行的问题[https://github.com/TechXueXi/TechXueXi/issues/78]
        for cookie in cookies:
            if cookie['domain'] == 'pc.xuexi.cn':
                self.driver.get("https://pc.xuexi.cn/")
            if cookie['domain'] == '.xuexi.cn':
                self.driver.get("https://www.xuexi.cn/")
            # print(f'current cookie: {cookie}')
            self.driver.add_cookie(cookie)
    except exceptions.InvalidCookieDomainException as e:
        print(e.__str__)
```

**Comment by OliverYmy** [comment]
> @OliverYmy
> 
> > @WANGJUNHAOmatt 感谢，我查到那个cookie新特性了，但不知道mydriver.py该怎么改orz
> 
> 客气啦，很期待可以帮到你，我已经提交了Pull Requests
> 请点击链接查看->#88
> 
> 或者可以直接修改 mydriver.py 中131行左右的 `set_cookies()` 函数为如下：
> 
> ```python
> def set_cookies(self, cookies):
>     try:
>         # 解决Chrome 90版本无法运行的问题[https://github.com/TechXueXi/TechXueXi/issues/78]
>         for cookie in cookies:
>             print(cookie)
>             self.driver.add_cookie({k: cookie[k] for k in cookie.keys()})
>             #self.driver.add_cookie(cookie)
>             if cookie['domain'] == 'pc.xuexi.cn':
>                 self.driver.get("https://pc.xuexi.cn/")
>             if cookie['domain'] == '.xuexi.cn':
>                 self.driver.get("https://www.xuexi.cn/")
>             # print(f'current cookie: {cookie}')
>             self.driver.add_cookie(cookie)
>     except exceptions.InvalidCookieDomainException as e:
>         print(e.__str__)
> ```

嗯嗯，已经修改了，运行正常
