### ISSUE TITLE
项目还有没有人维护

### ISSUE THREAD

**Issue by ec000** [power-helper/power-helper-backup20210704#8]
建议添加linux低版本chrome和chrome-dirver，最新版本直接get很难匹配
出现现象:
当前网络缓慢...
当前网络缓慢...
扫描二维码超时
运行环境华为云，系统DD为原生debian9
对应代码应该为pandalearning.py  line57  login()函数中get("https://pc.xuexi.cn/points/login.html")有问题，网站我直接使用浏览器是能打开，服务器上wget直接下载下来的html确实无法打开

**Comment by thinkrecord** [comment]
请使用带图形界面的环境,推荐windows。尽量使用自用电脑，最好不要使用vps,云主机等（因为有可能被xuexi根据服务商ip查到）。如果觉得代码可以优化请提交pr
