### ISSUE TITLE
无法扫码登陆

### ISSUE THREAD

**Issue by ggggggggggithub** [power-helper/power-helper-backup20210704#81]
**系统版本，包含位数**：win10 1809 64bit

**python版本**：3.8.3

**软件/源码版本**：20210306

**浏览器、驱动版本**：88.0.4324.190

-----

## 详细描述
答：弹出网页登陆二维码时浏览器闪退，报错

## 全部报错
答：

## 建议
答：

**Comment by LevineWoo** [comment]
我倒是想问怎么换别的账号。。

**Comment by mudapi** [comment]
> 我倒是想问怎么换别的账号。。

把user文件夹删掉咯~

**Comment by LevineWoo** [comment]
> > 我倒是想问怎么换别的账号。。
> 
> 把user文件夹删掉咯~

只能这样啦？

**Comment by TCPsoftware** [comment]
扫码登陆，使用其他人的扫描，登陆进入的就是其他人的
user文件夹中有学习记录等重要信息，不建议删除

**Comment by TCPsoftware** [comment]
使用新版本，如仍有问题，请重开此issue，并提供详细的问题和情况描述。
