### ISSUE TITLE
最新的5.19版本，替换exe文件后，无法运行，提示如下：

### ISSUE THREAD

**Issue by star2k** [power-helper/power-helper-backup20210704#98]
“缺少配置文件 config/main.ini，请检查.”
不动了！

**Comment by a18ccms** [comment]
你复制一份配置文件到exe文件所在位置就好了。结构就按提示就可以了。
配置文件正常就不应该打包进exe中。要不怎么改配置。。

**Comment by kinhuang1986** [comment]
同样的问题，按照把配置文件到exe文件所在位置后，没有解决。

**Comment by cyczq11** [comment]
我也是不行呀

**Comment by whuxxie** [comment]
复制配置文件了也不行

**Comment by a18ccms** [comment]
> 
> 
> 你复制一份配置文件到exe文件所在位置就好了。结构就按提示就可以了。
> 配置文件正常就不应该打包进exe中。要不怎么改配置。。

结构是按提示吗？要新建config文件夹。main.ini放里面。

**Comment by whuxxie** [comment]
> 你复制一份配置文件到exe文件所在位置就好了。结构就按提示就可以了。
> 配置文件正常就不应该打包进exe中。要不怎么改配置。。

你试过没有呀，建了config文件夹，放了main.ini文件，还是没用

**Comment by a18ccms** [comment]
@tobctobc 你改错文件了。#75 里面我说的是修改pandalearning.py的目录。不要修改config.py。
```
if __name__ == '__main__':
    # 注：不要再pandalearning.py之外使用os.chdir(sys.path[0])，否则可能造成打包程序不能运行
    # os.chdir(sys.path[0]) # 切换pwd到python文件路径，避免找不到相对路径下的ini和相关文件
    base_path = getattr(sys, '_MEIPASS', os.path.abspath('.'))
    os.chdir(base_path)
```

**Comment by a18ccms** [comment]
> 
> 
> > 你复制一份配置文件到exe文件所在位置就好了。结构就按提示就可以了。
> > 配置文件正常就不应该打包进exe中。要不怎么改配置。。
> 
> 你试过没有呀，建了config文件夹，放了main.ini文件，还是没用

不好意思。。我确实没试。

**Comment by YeQiuO** [comment]
有大佬知道为什么嘛..
救救孩子吧
![image](https://user-images.githubusercontent.com/45990941/118917749-24312200-b964-11eb-8157-78318e7c2af1.png)

**Comment by star2k** [comment]
> main.ini



> @tobctobc 你改错文件了。#75 里面我说的是修改pandalearning.py的目录。不要修改config.py。
> 
> ```
> if __name__ == '__main__':
>     # 注：不要再pandalearning.py之外使用os.chdir(sys.path[0])，否则可能造成打包程序不能运行
>     # os.chdir(sys.path[0]) # 切换pwd到python文件路径，避免找不到相对路径下的ini和相关文件
>     base_path = getattr(sys, '_MEIPASS', os.path.abspath('.'))
>     os.chdir(base_path)
> ```

没找到这个pandalearning.py文件夹不知道如何修改，main.ini又怎么获取？

**Comment by thinkrecord** [comment]
使用 v20210520 新版。

**Comment by TCPsoftware** [comment]
> @tobctobc 你改错文件了。#75 里面我说的是修改pandalearning.py的目录。不要修改config.py。
> 
> ```
> if __name__ == '__main__':
>     # 注：不要再pandalearning.py之外使用os.chdir(sys.path[0])，否则可能造成打包程序不能运行
>     # os.chdir(sys.path[0]) # 切换pwd到python文件路径，避免找不到相对路径下的ini和相关文件
>     base_path = getattr(sys, '_MEIPASS', os.path.abspath('.'))
>     os.chdir(base_path)
> ```

试过了，config.py使用新方法倒是没有问题，base_path正常，是pandalearning目录
